language: node_js
node_js:
  - '8'
cache: yarn
script:
  - yarn test

after_success: 
  - yarn global add codeclimate-test-reporter
  - yarn coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
